# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  #schedule:
  #  - cron: 0 20 * * *
  workflow_dispatch:
    inputs:
      param:
        description: 'parameter'
        required: false
        default: ''

permissions:
  contents: read

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: Update feeds
        run: |
          echo 'src-git helloworld https://github.com/fw876/helloworld' >> ./feeds.conf.default
          sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config
          cat >> .config <<EOF
          #
          # ========================固件定制部分========================
          #
          CONFIG_TARGET_x86=y

          CONFIG_TARGET_x86_generic=y

          CONFIG_TARGET_x86_generic_DEVICE_generic=y

          CONFIG_GNUTLS_ALPN=y

          CONFIG_GNUTLS_ANON=y

          CONFIG_GNUTLS_DTLS_SRTP=y

          CONFIG_GNUTLS_HEARTBEAT=y

          CONFIG_GNUTLS_OCSP=y

          CONFIG_GNUTLS_PSK=y

          CONFIG_IB=y

          CONFIG_IB_STANDALONE=y

          CONFIG_LIBCURL_COOKIES=y

          CONFIG_LIBCURL_FILE=y

          CONFIG_LIBCURL_FTP=y

          CONFIG_LIBCURL_HTTP=y

          CONFIG_LIBCURL_MBEDTLS=y

          CONFIG_LIBCURL_NGHTTP2=y

          CONFIG_LIBCURL_NO_SMB="!"

          CONFIG_LIBCURL_PROXY=y

          CONFIG_MAKE_TOOLCHAIN=y

          CONFIG_NFS_KERNEL_SERVER_V4=y

          CONFIG_OPENSSL_ENGINE=y

          CONFIG_OPENSSL_OPTIMIZE_SPEED=y

          CONFIG_OPENSSL_PREFER_CHACHA_OVER_GCM=y

          CONFIG_OPENSSL_WITH_ASM=y

          CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y

          CONFIG_OPENSSL_WITH_CMS=y

          CONFIG_OPENSSL_WITH_DEPRECATED=y

          CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y

          CONFIG_OPENSSL_WITH_PSK=y

          CONFIG_OPENSSL_WITH_SRP=y

          CONFIG_OPENSSL_WITH_SSE2=y

          CONFIG_OPENSSL_WITH_TLS13=y

          CONFIG_PACKAGE_alsa-lib=y

          CONFIG_PACKAGE_alsa-ucm-conf=y

          CONFIG_PACKAGE_alsa-utils=y

          CONFIG_PACKAGE_attr=y

          CONFIG_PACKAGE_avahi-dbus-daemon=y

          CONFIG_PACKAGE_bash=y

          CONFIG_PACKAGE_btrfs-progs=y

          CONFIG_PACKAGE_ca-certificates=y

          CONFIG_PACKAGE_cgi-io=y

          CONFIG_PACKAGE_containerd=y

          CONFIG_PACKAGE_coreutils=y

          CONFIG_PACKAGE_coreutils-base64=y

          CONFIG_PACKAGE_coreutils-nohup=y

          CONFIG_PACKAGE_coreutils-stty=y

          CONFIG_PACKAGE_cshark=y

          CONFIG_PACKAGE_curl=y

          CONFIG_PACKAGE_dbus=y

          CONFIG_PACKAGE_docker=y

          CONFIG_PACKAGE_dockerd=y

          CONFIG_PACKAGE_frpc=y

          CONFIG_PACKAGE_ip6tables-nft=y

          CONFIG_PACKAGE_ipset=y

          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y

          CONFIG_PACKAGE_iptables-mod-extra=y

          CONFIG_PACKAGE_iptables-mod-ipopt=y

          CONFIG_PACKAGE_iptables-mod-tproxy=y

          CONFIG_PACKAGE_iptables-nft=y

          CONFIG_PACKAGE_kmod-br-netfilter=y

          CONFIG_PACKAGE_kmod-crypto-acompress=y

          CONFIG_PACKAGE_kmod-crypto-aead=y

          CONFIG_PACKAGE_kmod-crypto-arc4=y

          CONFIG_PACKAGE_kmod-crypto-cbc=y

          CONFIG_PACKAGE_kmod-crypto-cts=y

          CONFIG_PACKAGE_kmod-crypto-des=y

          CONFIG_PACKAGE_kmod-crypto-ecb=y

          CONFIG_PACKAGE_kmod-crypto-hmac=y

          CONFIG_PACKAGE_kmod-crypto-manager=y

          CONFIG_PACKAGE_kmod-crypto-md5=y

          CONFIG_PACKAGE_kmod-crypto-null=y

          CONFIG_PACKAGE_kmod-crypto-rng=y

          CONFIG_PACKAGE_kmod-crypto-sha1=y

          CONFIG_PACKAGE_kmod-crypto-sha256=y

          CONFIG_PACKAGE_kmod-dax=y

          CONFIG_PACKAGE_kmod-dm=y

          CONFIG_PACKAGE_kmod-dnsresolver=y

          CONFIG_PACKAGE_kmod-fs-btrfs=y

          CONFIG_PACKAGE_kmod-fs-exportfs=y

          CONFIG_PACKAGE_kmod-fs-nfs=y

          CONFIG_PACKAGE_kmod-fs-nfs-common=y

          CONFIG_PACKAGE_kmod-fs-nfs-common-rpcsec=y

          CONFIG_PACKAGE_kmod-fs-nfs-v4=y

          CONFIG_PACKAGE_kmod-fs-nfsd=y

          CONFIG_PACKAGE_kmod-ifb=y

          CONFIG_PACKAGE_kmod-ip6tables=y

          CONFIG_PACKAGE_kmod-ipt-conntrack=y

          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y

          CONFIG_PACKAGE_kmod-ipt-core=y

          CONFIG_PACKAGE_kmod-ipt-extra=y

          CONFIG_PACKAGE_kmod-ipt-ipopt=y

          CONFIG_PACKAGE_kmod-ipt-ipset=y

          CONFIG_PACKAGE_kmod-ipt-nat=y

          CONFIG_PACKAGE_kmod-ipt-nat6=y

          CONFIG_PACKAGE_kmod-ipt-physdev=y

          CONFIG_PACKAGE_kmod-ipt-raw=y

          CONFIG_PACKAGE_kmod-ipt-tproxy=y

          CONFIG_PACKAGE_kmod-keys-encrypted=y

          CONFIG_PACKAGE_kmod-keys-trusted=y

          CONFIG_PACKAGE_kmod-lib-lzo=y

          CONFIG_PACKAGE_kmod-lib-raid6=y

          CONFIG_PACKAGE_kmod-lib-xor=y

          CONFIG_PACKAGE_kmod-lib-zlib-deflate=y

          CONFIG_PACKAGE_kmod-lib-zlib-inflate=y

          CONFIG_PACKAGE_kmod-lib-zstd=y

          CONFIG_PACKAGE_kmod-nf-ipt=y

          CONFIG_PACKAGE_kmod-nf-ipt6=y

          CONFIG_PACKAGE_kmod-nf-ipvs=y

          CONFIG_PACKAGE_kmod-nf-nat6=y

          CONFIG_PACKAGE_kmod-nft-compat=y

          # CONFIG_PACKAGE_kmod-nft-tproxy is not set

          CONFIG_PACKAGE_kmod-oid-registry=y

          CONFIG_PACKAGE_kmod-random-core=y

          CONFIG_PACKAGE_kmod-sched-connmark=y

          CONFIG_PACKAGE_kmod-sched-core=y

          CONFIG_PACKAGE_kmod-sound-core=y

          CONFIG_PACKAGE_kmod-tpm=y

          CONFIG_PACKAGE_kmod-tun=y

          CONFIG_PACKAGE_kmod-veth=y

          CONFIG_PACKAGE_libatomic=y

          CONFIG_PACKAGE_libattr=y

          CONFIG_PACKAGE_libavahi-client=y

          CONFIG_PACKAGE_libavahi-dbus-support=y

          CONFIG_PACKAGE_libcap=y

          CONFIG_PACKAGE_libconfig=y

          CONFIG_PACKAGE_libcurl=y

          CONFIG_PACKAGE_libdaemon=y

          CONFIG_PACKAGE_libdbus=y

          CONFIG_PACKAGE_libdevmapper=y

          CONFIG_PACKAGE_libexpat=y

          CONFIG_PACKAGE_libgmp=y

          CONFIG_PACKAGE_libgnutls=y

          CONFIG_PACKAGE_libipset=y

          CONFIG_PACKAGE_libiptext=y

          CONFIG_PACKAGE_libiptext-nft=y

          CONFIG_PACKAGE_libiptext6=y

          CONFIG_PACKAGE_libiwinfo=y

          CONFIG_PACKAGE_libiwinfo-data=y

          CONFIG_PACKAGE_libiwinfo-lua=y

          CONFIG_PACKAGE_libkeyutils=y

          CONFIG_PACKAGE_liblua=y

          CONFIG_PACKAGE_liblucihttp=y

          CONFIG_PACKAGE_liblucihttp-lua=y

          CONFIG_PACKAGE_liblzo=y

          CONFIG_PACKAGE_libmbedtls=y

          CONFIG_PACKAGE_libmount=y

          CONFIG_PACKAGE_libncurses=y

          CONFIG_PACKAGE_libnettle=y

          CONFIG_PACKAGE_libnetwork=y

          CONFIG_PACKAGE_libnghttp2=y

          CONFIG_PACKAGE_libopenssl=y

          CONFIG_PACKAGE_libpcap=y

          CONFIG_PACKAGE_libpopt=y

          CONFIG_PACKAGE_libreadline=y

          CONFIG_PACKAGE_libseccomp=y

          CONFIG_PACKAGE_libsoxr=y

          CONFIG_PACKAGE_libtasn1=y

          CONFIG_PACKAGE_libtirpc=y

          CONFIG_PACKAGE_libubus-lua=y

          CONFIG_PACKAGE_liburing=y

          CONFIG_PACKAGE_libustream-mbedtls=y

          CONFIG_PACKAGE_libustream-openssl=y

          CONFIG_PACKAGE_libustream-wolfssl=m

          CONFIG_PACKAGE_libuv=y

          CONFIG_PACKAGE_libwrap=y

          CONFIG_PACKAGE_libxtables=y

          CONFIG_PACKAGE_lsblk=y

          CONFIG_PACKAGE_lua=y

          CONFIG_PACKAGE_luci-app-airplay2=y

          CONFIG_PACKAGE_luci-app-clash=y

          CONFIG_PACKAGE_luci-app-cshark=y

          CONFIG_PACKAGE_luci-app-firewall=y

          CONFIG_PACKAGE_luci-app-frpc=y

          CONFIG_PACKAGE_luci-app-jellyfin=y

          CONFIG_PACKAGE_luci-app-nfs=y

          CONFIG_PACKAGE_luci-app-qos=y

          CONFIG_PACKAGE_luci-app-samba4=y

          CONFIG_PACKAGE_luci-app-udpxy=y

          CONFIG_PACKAGE_luci-base=y

          CONFIG_PACKAGE_luci-compat=y

          CONFIG_PACKAGE_luci-lib-base=y

          CONFIG_PACKAGE_luci-lib-ip=y

          CONFIG_PACKAGE_luci-lib-jsonc=y

          CONFIG_PACKAGE_luci-lib-nixio=y

          CONFIG_PACKAGE_luci-lib-taskd=y

          CONFIG_PACKAGE_luci-lib-xterm=y

          CONFIG_PACKAGE_luci-mod-dashboard=y

          CONFIG_PACKAGE_luci-mod-network=y

          CONFIG_PACKAGE_luci-mod-system=y

          CONFIG_PACKAGE_luci-theme-bootstrap=y

          CONFIG_PACKAGE_luci-theme-material=y

          CONFIG_PACKAGE_luci-theme-openwrt=y

          CONFIG_PACKAGE_luci-theme-openwrt-2020=y

          CONFIG_PACKAGE_mount-utils=y

          CONFIG_PACKAGE_netdata=y

          CONFIG_PACKAGE_nfs-kernel-server=y

          CONFIG_PACKAGE_nfs-kernel-server-utils=y

          CONFIG_PACKAGE_nfs-utils=y

          CONFIG_PACKAGE_nfs-utils-libs=y

          CONFIG_PACKAGE_qos-scripts=y

          CONFIG_PACKAGE_rpcbind=y

          CONFIG_PACKAGE_rpcd=y

          CONFIG_PACKAGE_rpcd-mod-file=y

          CONFIG_PACKAGE_rpcd-mod-iwinfo=y

          CONFIG_PACKAGE_rpcd-mod-luci=y

          CONFIG_PACKAGE_runc=y

          CONFIG_PACKAGE_samba4-libs=y

          CONFIG_PACKAGE_samba4-server=y

          CONFIG_PACKAGE_script-utils=y

          CONFIG_PACKAGE_shairport-sync-openssl=y

          CONFIG_PACKAGE_taskd=y

          CONFIG_PACKAGE_tc-tiny=y

          CONFIG_PACKAGE_terminfo=y

          CONFIG_PACKAGE_tini=y

          CONFIG_PACKAGE_udpxy=y

          CONFIG_PACKAGE_wsdd2=y

          CONFIG_PACKAGE_xray-core=y

          CONFIG_PACKAGE_xtables-nft=y

          CONFIG_PACKAGE_zlib=y

          CONFIG_RPCBIND_LIBWRAP=y

          CONFIG_RPCBIND_RMTCALLS=y

          CONFIG_SAMBA4_SERVER_AVAHI=y

          CONFIG_SAMBA4_SERVER_NETBIOS=y

          CONFIG_SAMBA4_SERVER_VFS=y

          CONFIG_SAMBA4_SERVER_WSDD2=y

          CONFIG_TARGET_KERNEL_PARTSIZE=128

          CONFIG_TARGET_ROOTFS_PARTSIZE=256

          # CONFIG_TARGET_ROOTFS_SQUASHFS is not set

          CONFIG_VDI_IMAGES=y

          CONFIG_PACKAGE_libwolfssl=y


          #
          # ========================固件定制部分结束========================
          #
          EOF
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
